### ISSUE TITLE
'PyRanges object has no attribute', 'Count' 

### ISSUE THREAD

**Issue by laki-spk** [aertslab/scenicplus#437]
Hi @SeppeDeWinter and team

This is a great tool and thank you for establishing this. I've been using this with several data types and I'd no issue before. But now I am running it with Human data set, and it is working up to the MAC2 calling step. 

But I can't move fast the following script and I am getting the following error;

```

> from pycisTopic.iterative_peak_calling import get_consensus_peaks
> # Other param
> peak_half_width = 250
> path_to_blacklist= '/temp_work/ch250798/Scenic/pycisTopic/blacklist/hg38-blacklist.v2.bed'
> # Get consensus peaks
> 
> narrow_peaks_dict = pickle.load(open(os.path.join(work_dir, 'scATACkk/consensus_peak_calling/MACS/narrow_peaks_dict.pkl'), 'rb')) 
> consensus_peaks=get_consensus_peaks(narrow_peaks_dict, peak_half_width, chromsizes=chromsizes, path_to_blacklist=path_to_blacklist)

```
![image](https://github.com/user-attachments/assets/27ceebd7-da75-40fa-ba3d-fc4ace3b28fa)

Could you please help me troubleshoot this issue?

Thank you

**Comment by laki-spk** [comment]
Never mind I was able to resolve it.

**Comment by SBonsall** [comment]
I am having the exact same issue - How did you resolve this?

Edit: I've found what looks to be causing the issue in my case - It seems to be related to the number of cells assigned to each subclass in my original cistopic object/cell data. Running something like this, using a specific key from narrow_peak_dict.:

```
consensus_peaks = get_consensus_peaks(
    narrow_peaks_dict = narrow_peak_dict['L5_IT'],
    peak_half_width = peak_half_width,
    chromsizes = chromsizes,
    path_to_blacklist = path_to_blacklist)
```
Seemed to work:

`2025-01-16 08:52:08,000 cisTopic     INFO     Extending and merging peaks per class`
`2025-01-16 08:52:13,951 cisTopic     INFO     Normalizing peak scores`
`2025-01-16 08:52:13,988 cisTopic     INFO     Merging peaks`
`Warning! Start and End columns now have different dtypes: int64 and int32`
`2025-01-16 08:52:15,083 cisTopic     INFO     Done!`


I then ran this:

```
for i in narrow_peak_dict:
    try:
        print(f"Processing {i}...")

         consensus_peaks = get_consensus_peaks(
            narrow_peaks_dict=narrow_peak_dict[i],
            peak_half_width=peak_half_width,
            chromsizes=chromsizes,
            path_to_blacklist=path_to_blacklist
        )
        
        print(f"Successfully processed {i}.\n")
        
    except Exception as e:
        print(f"Error processing {i}: {e}\n")


```
to isolate the cell subclasses which were causing the error when using narrow_peak_dict. Sure enough:
```
Processing L5_IT...
2025-01-16 08:56:28,121 cisTopic     INFO     Extending and merging peaks per class
2025-01-16 08:56:34,119 cisTopic     INFO     Normalizing peak scores
2025-01-16 08:56:34,154 cisTopic     INFO     Merging peaks
Warning! Start and End columns now have different dtypes: int64 and int32
2025-01-16 08:56:35,200 cisTopic     INFO     Done!
Successfully processed L5_IT.

Processing L5_ET...
2025-01-16 08:56:35,215 cisTopic     INFO     Extending and merging peaks per class
Error processing L5_ET: ('PyRanges object has no attribute', 'Count')
```
Shows that it isn't the original narrow_peak_dict, rather the individual objects that it references.

Doing something like:
```
print(cistopic.cell_data['Subclass'].value_counts())
```
```
Oligo         18070
Astro          2827
L2_3_IT        2350
L5_IT          1323
Micro-PVM      1310
OPC            1252
Pvalb           585
Sst             497
L6_IT           382
Vip             341
Lamp5           328
Endo            296
L6b             191
L6_CT           167
L5_6_NP         114
L6_IT_Car3       74
Sncg             68
VLMC             67
L5_ET            51
Sst_Chodl        18
Name: Subclass, dtype: int64
```
Shows that this error is probably related to an inadequate number of cells to derive consensus peaks for that particular subclass. 
For reference, get_consensus_peaks failed for all of my cell subtypes including and underneath Pvalb. I haven't tried yet but I am assuming omitting cell subclasses with relatively few cells will fix this issue. 

I hope this helps anybody else experiencing that same issue!

EDIT 2: Further to this - it looks like it is actually also related to blacklist region filtering. Removing the path_to_blacklist argument results in all of my cell subclasses running without any errors. It makes sense that this would correlate with subclasses with fewer cells, since a large proportion of ATAC reads fall into blacklisted regions [[Ref 1](https://www.nature.com/articles/s41598-019-45839-z) [Ref 2](https://docs.google.com/spreadsheets/d/1G4SkqUMiGcUlvR6homc7RW33nSOf4mS9QYJifsd4qo0/edit?gid=9#gid=9)]. I would probably not recommend removing this argument though!
