### ISSUE TITLE
What's the meaning of the suffix of output eregulon's name like "+/+" or "+/-" ?

### ISSUE THREAD

**Issue by XinWang19** [aertslab/scenicplus#488]
Hi, I am trying to understand the output of SCENIC+ pipeline. Then I saw different eregulons of particular TF, like ETS1_direct_+/- and ETS1_direct_+/+. What are the meanings?

**Comment by yojetsharma** [comment]
https://github.com/aertslab/scenicplus/issues/466#issuecomment-2348281105 
It’s also present in the API part of the tutorial in detail.

**Comment by etalouarn** [comment]
Hello,
First of all, I want to thank you for the very nice tool !
I am pretty new in the ATACseq analysis field and the pycistopic and scenic+ have been a tremendous resource.

I have found the table the previous comment refers to and in which is specified what do the main categories mean. However, I find it pretty difficult to interpret.
Shouldn't there be more than 4 categories depending on: the expression of the TF, the open/closed status of the putative enhancer and the expression of the target gene? Myquestion might be naïve but is there a biological reason why some sub-categories should be grouped together?

According to this table, the "+/-" refers to : "When the TF is expressed the target gene is also expressed but the regions linked to the gene are closed." but then, does that mean that the putative enhancer has no effect in the end (since it is closed)?
I also don't quite understand the "-/+" category : "When the TF is expressed the target gene is not expressed. When the target gene is expressed, regions linked to this gene are open. TF could be a chromatin closing repressor.". The first sentence tells me that the TF indeed has an effect on the target gene but says nothing about the status of the putative enhancer. Is it closed? The second sentence however says that when the target gene is expressed, regions linked to it are open. In the scenario referred to in this second sentence is the TF expressed?  The third sentence is even more confusing. It states that the TF could be a chromatin closing repressor. This sentence assumes that the TF is expressed (and aludes to a function)? Is this correct?
Finally, I have the same problem with the "-/-" category: "When the TF is expressed the target gene is not. When target gene is expressed, regions linked to this gene are closed". First sentence doesn't specify what is the status of the putative enhancer. Second one, doesn't say whether the TF is expressed.

Thank you for your help !

**Comment by wdg118** [comment]
> Hello, First of all, I want to thank you for the very nice tool ! I am pretty new in the ATACseq analysis field and the pycistopic and scenic+ have been a tremendous resource.
> 
> I have found the table the previous comment refers to and in which is specified what do the main categories mean. However, I find it pretty difficult to interpret. Shouldn't there be more than 4 categories depending on: the expression of the TF, the open/closed status of the putative enhancer and the expression of the target gene? Myquestion might be naïve but is there a biological reason why some sub-categories should be grouped together?
> 
> According to this table, the "+/-" refers to : "When the TF is expressed the target gene is also expressed but the regions linked to the gene are closed." but then, does that mean that the putative enhancer has no effect in the end (since it is closed)? I also don't quite understand the "-/+" category : "When the TF is expressed the target gene is not expressed. When the target gene is expressed, regions linked to this gene are open. TF could be a chromatin closing repressor.". The first sentence tells me that the TF indeed has an effect on the target gene but says nothing about the status of the putative enhancer. Is it closed? The second sentence however says that when the target gene is expressed, regions linked to it are open. In the scenario referred to in this second sentence is the TF expressed? The third sentence is even more confusing. It states that the TF could be a chromatin closing repressor. This sentence assumes that the TF is expressed (and aludes to a function)? Is this correct? Finally, I have the same problem with the "-/-" category: "When the TF is expressed the target gene is not. When target gene is expressed, regions linked to this gene are closed". First sentence doesn't specify what is the status of the putative enhancer. Second one, doesn't say whether the TF is expressed.
> 
> Thank you for your help !

I'm a bit confused about this as well. The language is confusing. @SeppeDeWinter
